### ISSUE TITLE
UI and other enhancements

### ISSUE THREAD

**Issue by gunalabs** [guhan29/ratebeer#2]
Currently, The Ruby on Rails project currently lacks any styling, which affects both its usability and aesthetics. This issue is to track the implementation of styling across the project to improve user experience and visual appeal.

**Comment by gunalabs** [comment]
### Step 1: Fixing Style Errors
To resolve the style errors in your codebase to adhere to our defined styling rules, follow these steps:
1. **Identify Errors**: Run RuboCop with specific file or directory targets to pinpoint style violations:
2. **Fixing Errors**: Address each reported style error based on RuboCop's recommendations. Some errors may have auto fix suggestions.
3. **Documentation**: Refer to RuboCop's documentation for detailed explanations of each error:
   - [RuboCop Documentation](https://docs.rubocop.org/)

### Step 2: Adding a New Rule
To enforce a rule that forbids methods over 15 lines long:
1. **Rule Definition**: Configure RuboCop's configuration file (`rubocop.yml`) to include:
```yaml
Metrics/MethodLength:
  Max: 15
```
2. Checking Method Length: Run RuboCop to verify that it correctly identifies methods exceeding 15 lines.
3. Review and Refactor: If RuboCop detects methods violating this rule, refactor them accordingly to improve readability and maintainability.

**Comment by gunalabs** [comment]
### Enhancement: Modify Navigation Bar in Application Layout

#### Description:
Modify the navigation bar in the application layout to include the following functionalities:

1. Add links to sign in and sign out using HTTP DELETE for signing out.
2. Include a link to a page listing all users.
3. Display the signed-in user's username as a link to their personal page.
4. Show a link to create a new beer rating when the user is signed in.

#### Steps to Implement:

1. **Modify Navigation Bar for Sign In/Out:**
   - Update the application layout to include links for signing in and signing out.
   - Ensure signing out functionality uses HTTP DELETE method.

2. **Add Link to Page with All Users:**
   - Integrate a link in the navigation bar to navigate to a page listing all users.
   - Utilize appropriate path helpers based on defined routes (`rails routes` or inspect routes file).

3. **Display Signed-In User's Username:**
   - Conditionally display the username of the signed-in user.
   - Make the username a link that redirects to the user's personal page.

4. **Link to Create New Beer Rating:**
   - When a user is signed in, provide a link in the navigation bar to create a new beer rating.
   - Ensure the link is only visible to authenticated users.

#### Expected Result:
Upon completion of this exercise, the application's navigation bar should dynamically adjust based on the user's authentication status:
- Display links for signing in and out.
- Include a link to view all users.
- Show the signed-in user's username as a link to their profile.
- Provide a link to create a new beer rating when authenticated.

#### Additional Information:
- Rails version: 7.0.x
- Consider using `link_to` helpers and conditional logic to achieve the desired navigation bar functionality.
- Ensure routes and path helpers are correctly utilized for all links.

#### Related Documentation:
- Rails routing: [Rails Routing Guide](https://guides.rubyonrails.org/routing.html)
- ActionView `link_to` method: [ActionView Helpers](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to)

#### Priority:
This issue should be addressed promptly to enhance user experience and functionality within the application.

**Comment by guhan29** [comment]
/prompt Who is the owner of this issue?

**Comment by guhan29** [comment]
/prompt What are the updated needed to be done here to resolve the issue

**Comment by guhan29** [comment]
/prompt What are the updated needed to be done here to resolve the issue

**Comment by guhan29** [comment]
/prompt what are all the modifications that needs to be done?

**Comment by guhan29** [comment]
/prompt who is the owner of this issue?

**Comment by guhan29** [comment]
/prompt who is the author of this issue?

**Comment by guhan29** [comment]
/prompt who is the owner of this issue?

**Comment by guhan29** [comment]
/prompt what are the modifications that needs to be done?

**Comment by guhan29** [comment]
/prompt who is the owner of this issue?

**Comment by guhan29** [comment]
/prompt what are all the modifications that needs to be done?
